as_paperclip_bridge:
  repo: git://github.com/cliotropic/as_paperclip_bridge.git
  path: vendor/plugins
paperclip:
  repo: git://github.com/thoughtbot/paperclip.git
  path: vendor/thoughtbot
redbox:
  repo: git://github.com/craigambrose/redbox.git
  path: vendor/plugins
render_component:
  repo: http://github.com/rails/render_component.git
  path: vendor/plugins
active_scaffold:
  repo: git://github.com/activescaffold/active_scaffold.git
  path: vendor/plugins
